### ISSUE TITLE
Domain-wise binding affinities

### ISSUE THREAD

**Issue by rraadd88** [haddocking/prodigy#13]
Hi again, 
A quick question: Would it be possible to calculate binding affinity for a defined section of the interface e.g. protein domain, with the method used by prodigy?
It seems that prodigy (in its current version) is designed to estimate the binding affinities for entire binding interface. Out of curiosity, I wonder if there any possibility that this method could be used to obtain domain-wise binding affinities.
Thanks.

**Comment by schaarj** [comment]
you can split the protein into the domains and give each domain a separate chain ID. You should However take into account that the numbers produced might not be as reliable if those interfaces differ significantly from the interfaces prodigy was trained with. Also please use the forum (https://ask.bioexcel.eu/c/prodigy/) instead of issues to post questions
